# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.migration.version", 1);
user_pref("browser.startup.homepage", "http://pixelache.ac");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.8");
