.TH med-config 1 "Oct 18, 2007" "Debian-Med"
.SH NAME
med-config \- general Debian-Med package information and auto-apt helper
med-<meta_package_name> \- Debian-Med package information and auto-apt helper

.SH SYNOPSIS
.B med-config
.B med-<meta_package_name>

.SH DESCRIPTION
Print just a simple information page about every med-* package
of the Debian-Med Custom Debian Distribution.  Each metapackage has a 
.I /usr/bin/med-<meta_package_name>
file which should print some usefull informations and could be serve
as auto-apt helper.

.SH AUTHOR
Andreas Tille <tille@debian.org>.
